from django import forms
from knapsack_solution.models import KnapsackResults


class Predict_Form(forms.ModelForm):
    class Meta:
        model = KnapsackResults

        fields = (
                'appliance1',
                'appliance2',
                'appliance3',
                'appliance4',
                'appliance5',
                'appliance6',
                'appliance7',
                'appliance8',
                'appliance9',
                'appliance10',
                'priority1',
                'priority2',
                'priority3',
                'priority4',
                'priority5',
                'priority6',
                'priority7',
                'priority8',
                'priority9',
                'priority10',
                'time1',
                'time2',
                'time3',
                'time4',
                'time5',
                'time6',
                'time7',
                'time8',
                'time9',
                'time10',
                'price_of_electricity',
                'price_of_high_tariffs',
                'limit_of_time_hours',
        )

        widgets = {'appliance1': forms.Select(attrs={'class': 'form-control'}),
                   'appliance2': forms.Select(attrs={'class': 'form-control'}),
                   'appliance3': forms.Select(attrs={'class': 'form-control'}),
                   'appliance4': forms.Select(attrs={'class': 'form-control'}),
                   'appliance5': forms.Select(attrs={'class': 'form-control'}),
                   'appliance6': forms.Select(attrs={'class': 'form-control'}),
                   'appliance7': forms.Select(attrs={'class': 'form-control'}),
                   'appliance8': forms.Select(attrs={'class': 'form-control'}),
                   'appliance9': forms.Select(attrs={'class': 'form-control'}),
                   'appliance10': forms.Select(attrs={'class': 'form-control'}),
                   'priority1': forms.Select(attrs={'class': 'form-control'}),
                   'priority2': forms.Select(attrs={'class': 'form-control'}),
                   'priority3': forms.Select(attrs={'class': 'form-control'}),
                   'priority4': forms.Select(attrs={'class': 'form-control'}),
                   'priority5': forms.Select(attrs={'class': 'form-control'}),
                   'priority6': forms.Select(attrs={'class': 'form-control'}),
                   'priority7': forms.Select(attrs={'class': 'form-control'}),
                   'priority8': forms.Select(attrs={'class': 'form-control'}),
                   'priority9': forms.Select(attrs={'class': 'form-control'}),
                   'priority10': forms.Select(attrs={'class': 'form-control'}),
                   'time1': forms.TextInput(attrs={'class': 'form-control'}),
                   'time2': forms.TextInput(attrs={'class': 'form-control'}),
                   'time3': forms.TextInput(attrs={'class': 'form-control'}),
                   'time4': forms.TextInput(attrs={'class': 'form-control'}),
                   'time5': forms.TextInput(attrs={'class': 'form-control'}),
                   'time6': forms.TextInput(attrs={'class': 'form-control'}),
                   'time7': forms.TextInput(attrs={'class': 'form-control'}),
                   'time8': forms.TextInput(attrs={'class': 'form-control'}),
                   'time9': forms.TextInput(attrs={'class': 'form-control'}),
                   'time10': forms.TextInput(attrs={'class': 'form-control'}),
                   'price_of_electricity': forms.TextInput(attrs={'class': 'form-control'}),
                   'price_of_high_tariffs': forms.TextInput(attrs={'class': 'form-control'}),
                   'limit_of_time_hours':  forms.TextInput(attrs={'class': 'form-control'}),
                   }
