# Generated by Django 2.2.24 on 2022-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='KnapsackResults',
            name='fasting_blood_sugar',
            field=models.IntegerField(choices=[(1, '> 120 mg/dl'), (0, '< 120 mg/dl')], default=0),
        ),
    ]
