# Generated by Django 2.2.24 on 2022-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0002_auto_0601_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='KnapsackResults',
            name='cp',
            field=models.IntegerField(choices=[(0, 'None'),
                                               (1, 'Typical Angina'),
                                               (2, 'Atypical Angina'),
                                               (3, 'Non-Angina'),
                                               (4, 'Asymptomatic')], default=0),
        ),
    ]
