# Generated by Django 3.2.5 on 2022-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0003_auto_0601_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance1',
            field=models.IntegerField(choices=[(1200, 'Coffee maker'), (500, 'Clothes washer'), (5000, 'Clothes dryer'), (2400, 'Dishwasher'), (2400, 'Dishwasher')], default=0),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
