# Generated by Django 3.2.5 on 2022-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0004_auto_20220205_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance1',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer'), (5000, 'Clothes dryer'), (2400, 'Dishwasher'), (2400, 'Dishwasher')], default=0),
        ),
    ]
