# Generated by Django 3.2.5 on 2022-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0005_alter_knapsackresults_appliance1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance1',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
    ]
