# Generated by Django 3.2.5 on 2022-02-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0006_alter_knapsackresults_appliance1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knapsackresults',
            old_name='age',
            new_name='price_of_electricity',
        ),
        migrations.RenameField(
            model_name='knapsackresults',
            old_name='max_heart_rate',
            new_name='price_of_high_tariffs',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='exercise_induced_angina',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='fasting_blood_sugar',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='num',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='number_of_vessels',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='resting_bp',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='resting_ecg',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='serum_cholesterol',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='st_depression',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='st_slope',
        ),
        migrations.RemoveField(
            model_name='knapsackresults',
            name='thallium_scan_results',
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance10',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance11',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance12',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance13',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance14',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance15',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance2',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance3',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance4',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance5',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance6',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance7',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance8',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='appliance9',
            field=models.IntegerField(choices=[(0, 'None'), (1200, 'Coffee maker - 1200 Watts'), (500, 'Clothes washer - 500 Watts'), (5000, 'Clothes dryer - 5000 Watts'), (2400, 'Dishwasher - 2400 Watts'), (2400, 'Dishwasher - 2400 Watts'), (1875, 'Hair dryer - 1875 Watts'), (1500, 'Heater - 1500 Watts'), (1800, 'Clothes iron - 1800 Watts'), (1100, 'Microwave oven - 1100 Watts'), (50, 'Laptop - 50 Watts'), (400, 'Radio - 400 Watts'), (725, 'Refrigerator - 725 Watts'), (110, 'Television - 110 Watts')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority1',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority10',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority11',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority12',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority13',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority14',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority15',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority2',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority3',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority4',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority5',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority6',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority7',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority8',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='priority9',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=0),
        ),
    ]
