# Generated by Django 3.2.5 on 2022-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0009_auto_20220206_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance1',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance10',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance2',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance3',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance4',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance5',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance6',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance7',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance8',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='appliance9',
            field=models.CharField(choices=[('', 'None'), ('Coffee maker', 'Coffee maker - 1200 Watts'), ('Clothes washer', 'Clothes washer - 500 Watts'), ('Clothes dryer', 'Clothes dryer - 5000 Watts'), ('Clothes dryer', 'Dishwasher - 2400 Watts'), ('Hair dryer', 'Hair dryer - 1875 Watts'), ('Heater', 'Heater - 1500 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Microwave oven', 'Microwave oven - 1100 Watts'), ('Laptop', 'Laptop - 50 Watts'), ('Radio', 'Radio - 400 Watts'), ('Refrigerator', 'Refrigerator - 725 Watts'), ('Television', 'Television - 110 Watts'), ('Vacuum cleaner', 'Vacuum cleaner - 1440 Watts'), ('Clothes iron', 'Clothes iron - 1800 Watts'), ('Toaster', 'Toaster - 1400 Watts'), ('Ceiling Fans', 'Ceiling Fans - 110 Watts')], default='', max_length=30),
        ),
    ]
