# Generated by Django 3.2.5 on 2022-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0011_auto_20220206_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='knapsackresults',
            name='time1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackresults',
            name='time9',
            field=models.IntegerField(default=0),
        ),
    ]
