# Generated by Django 3.2.5 on 2022-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack_solution', '0012_auto_20220207_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='knapsackresults',
            name='limit_of_time_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='price_of_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knapsackresults',
            name='price_of_high_tariffs',
            field=models.IntegerField(default=0),
        ),
    ]
